api:
  dashboard: true
  debug: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

log:
  level: DEBUG
  filePath: "/logs/traefik.log"
  format: common

accessLog:
  filePath: "/logs/access.log"
  bufferingSize: 100
  format: common

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    swarmMode: true
    exposedByDefault: false
  file:
    filename: config.yml

#certificatesResolvers:
#  myresolver:
#    acme:
#      email: john.watkins@springdox.com
#      storage: acme.json
#      httpChallenge:
        # used during the challenge
#        entryPoint: web